# Generated by Django 4.0 on 2021-12-08 15:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cjepivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cjepivo_naziv', models.CharField(max_length=30)),
                ('broj_doza', models.CharField(max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='student_cijepljen',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='student_datumCijepljenja',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='student',
            name='student_prebolio',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Zaposlenik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zaposlenik_ime', models.CharField(max_length=30)),
                ('zaposlenik_prezime', models.CharField(max_length=30)),
                ('zaposlenik_oib', models.CharField(max_length=11)),
                ('zaposlenik_cijepljen', models.BooleanField(default=True)),
                ('zaposlenik_datumCijepljenja', models.DateTimeField(default=django.utils.timezone.now)),
                ('zaposlenik_prebolio', models.BooleanField(default=False)),
                ('zaposlenik_cjepivo', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='main.cjepivo')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='student_cjepivo',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='main.cjepivo'),
        ),
    ]
