# Generated by Django 4.0 on 2021-12-08 16:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_cjepivo_student_student_cijepljen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fakultet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fakultet_naziv', models.CharField(max_length=30)),
                ('fakultet_adresa', models.CharField(max_length=30)),
                ('fakultet_kontakt_broj', models.CharField(max_length=20)),
                ('fakultet_email_referade', models.EmailField(default='', max_length=254)),
                ('fakultet_website', models.URLField()),
            ],
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_datumCijepljenja',
            new_name='student_datum_cijepljenja',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_prebolio',
            new_name='student_prebolio_covid',
        ),
        migrations.RenameField(
            model_name='zaposlenik',
            old_name='zaposlenik_datumCijepljenja',
            new_name='zaposlenik_datum_cijepljenja',
        ),
        migrations.RenameField(
            model_name='zaposlenik',
            old_name='zaposlenik_prebolio',
            new_name='zaposlenik_prebolio_covid',
        ),
        migrations.AddField(
            model_name='student',
            name='student_datum_isteka_potvrde',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='student',
            name='student_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='zaposlenik',
            name='zaposlenik_datum_isteka_potvrde',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='zaposlenik',
            name='zaposlenik_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='student',
            name='student_fakultet',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='main.fakultet'),
        ),
        migrations.AddField(
            model_name='zaposlenik',
            name='zaposlenik_fakultet',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.fakultet'),
        ),
    ]
