# Generated by Django 4.0 on 2021-12-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_fakultet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.RemoveField(
            model_name='zaposlenik',
            name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='student_jmbag',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='zaposlenik',
            name='zaposlenik_oib',
            field=models.CharField(max_length=11, primary_key=True, serialize=False),
        ),
    ]
