# Generated by Django 4.0 on 2021-12-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_student_id_remove_zaposlenik_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_adresa',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='zaposlenik',
            name='zaposlenik_adresa',
            field=models.CharField(default='', max_length=30),
        ),
    ]
