# Generated by Django 4.0.2 on 2022-02-23 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_student_student_cjepivo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_fakultet',
        ),
        migrations.AddField(
            model_name='student',
            name='student_fakultet',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.fakultet'),
        ),
        migrations.RemoveField(
            model_name='zaposlenik',
            name='zaposlenik_fakultet',
        ),
        migrations.AddField(
            model_name='zaposlenik',
            name='zaposlenik_fakultet',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.fakultet'),
        ),
    ]
